### ISSUE TITLE
Out of Date Certificate

### ISSUE THREAD

**Issue by TroyNeubauer** [defuse/defuse.ca#13]
Today while working on a ctf, I needed to assemble some code so I went to my favorite website for doing so: https://defuse.ca/online-x86-assembler.htm
Unless I am being hacked I think you need to update your certificate.

![image](https://user-images.githubusercontent.com/13263959/57984100-318a3d80-7a26-11e9-8b6f-2aad85c69d47.png)

**Comment by defuse** [comment]
Yeah, you weren't hacked. The let's encrypt cron job failed. Thanks!
