### ISSUE TITLE
Can I ask you a question about online assembly site? 

### ISSUE THREAD

**Issue by Richyeoh** [defuse/defuse.ca#22]
I'd like to ask how the web version of assembly is made, because I want to write a simple assembly compiler

**Comment by Richyeoh** [comment]
I downloaded the source code of your website, Now maybe I already how to do it.

**Comment by defuse** [comment]
Yeah, it just uses GCC under the hood. :-)

**Comment by Richyeoh** [comment]
Thanks, In your website, I learned a lot.

**Comment by defuse** [comment]
Sweet thanks :)
