### ISSUE TITLE
Online assembly: hex constants

### ISSUE THREAD

**Issue by Carmina16** [defuse/defuse.ca#29]
It doesn't seem to support hexadecimal numbers:
``` asm
sub al, 0dfh-'a'
```
gives

`Error: junk `fh-97' after expression`

**Comment by defuse** [comment]
`sub al, 0dfh-'a'` looks malformed to me, a hexadecimal number would be something like `sub al, 0x1234`, `0dfh-'a'` is not a hexadecimal number. Feel free to reopen if you feel this is wrong.
